sonar.projectKey=gymtrack
sonar.projectName=GymTrack
sonar.organization=gymtrack-tecmilenio
sonar.sources=src,public
sonar.tests=tests
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
